#!/bin/sh

if [ -d /run/systemd/system ] && [ "$1" = "configure" ]; then
   systemctl --system daemon-reload >/dev/null || true
   if [ -n "$2" ]; then
      systemctl try-restart DCore || true
   fi
   systemctl enable DCore || true
fi
